# Generated by Django 2.2.17 on 2021-01-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
    ]
