# Generated by Django 2.2.17 on 2021-01-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_comment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.SlugField(default='0', editable=False),
        ),
    ]
