# Generated by Django 2.2.17 on 2021-01-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210119_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_vn',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_vn',
        ),
    ]
