# Generated by Django 2.2.17 on 2021-01-28 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default='0', to=settings.AUTH_USER_MODEL),
        ),
    ]
