# Generated by Django 2.2.17 on 2021-01-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210117_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(null=True),
        ),
    ]
